// Textos próprios da variante Mostruário (só PT). Não acrescentam factos: nada de números de obras, equipa, prazos ou preços.
export const C = {
  home: 'Início',
  contents: 'Navegação principal',
  quick: 'Ações rápidas',
  quoteShort: 'Orçamento',
  heroH: 'Construímos, reconstruímos e remodelamos no Algarve desde 1985.',
  heroLead: 'Moradias, reconstruções, remodelações, piscinas, telhados e obras públicas, com alvará nº 4511.',
  heroLead2: 'Cada amostra vem de uma obra nossa: passe por cima ou toque para ver a casa.',
  heroLead2m: 'Cada amostra vem de uma obra nossa: toque para ver a casa.',
  heroWa: 'Falar por WhatsApp',
  wallLabel: 'Amostras tiradas das obras da Civilsul',
  applied: 'Aplicado em',
  ref: 'Ref.',
  family: {
    moradias: 'Moradias',
    reconstrucao: 'Reconstrução',
    remodelacoes: 'Remodelações',
    piscinas: 'Piscinas e exteriores',
    telhados: 'Telhados',
    'obras-publicas': 'Obras públicas',
  } as Record<string, string>,
  servicesH: 'Seis famílias de trabalho, feitas pela mesma empresa.',
  servicesLead: 'Cada família junta os ofícios que uma obra desse tipo pede. As amostras mostram onde já os aplicámos.',
  seeService: 'Ver o serviço',
  worksH: 'As casas de onde vêm as amostras.',
  worksLead: 'Moradias construídas e reconstruídas, apartamentos remodelados, uma fachada preservada, piscinas e exteriores.',
  seeWorks: 'Ver todas as obras',
  companyH: 'Quem assina as obras.',
  specTitle: 'Ficha da empresa',
  spec: {
    legal: 'Empresa',
    since: 'Em atividade desde',
    permit: 'Alvará de construção',
    seat: 'Sede',
    area: 'Onde trabalha',
  },
  processH: 'Como trabalhamos',
  tradesH: 'Todos os trabalhos que fazemos',
  tradesLead: 'A lista completa, tal como a Civilsul a apresenta. Se procura um ofício em concreto, está aqui.',
  finalH: 'Monte a sua amostra.',
  finalLead: 'Diga-nos que obra quer fazer, onde e para quando. Em quatro passos, o pedido segue por WhatsApp ou email.',
  orCall: 'Ou fale connosco diretamente',
  aboutMore: 'Conhecer a empresa',
  // Serviços
  servicesPageH: 'Serviços',
  servicesPageLead: 'Da moradia nova à reparação de um telhado. Seis famílias de trabalho, cada uma com as amostras das obras onde foi aplicada.',
  items: 'O que inclui',
  fromWorks: 'Amostras desta família',
  otherServices: 'Outros serviços',
  askThis: 'Pedir orçamento para este serviço',
  // Obras
  worksPageH: 'Obras',
  worksPageLead: 'Obras do portefólio da Civilsul. Cada uma aparece primeiro como amostra do material e abre na fotografia da obra acabada.',
  filterLabel: 'Filtrar obras por tipo',
  all: 'Todas',
  shown: 'obras visíveis',
  kind: 'Tipo',
  place: 'Local',
  client: 'Cliente',
  service: 'Serviço',
  photoOf: 'Fotografia',
  prev: 'Obra anterior',
  next: 'Obra seguinte',
  workCtaH: 'Tem uma obra parecida em mente?',
  workCtaLead: 'Conte-nos o que quer fazer e onde. Respondemos para marcar uma visita e preparar o orçamento.',
  // Orçamento
  quoteH: 'Monte a sua amostra.',
  quoteLead: 'Escolha a obra, diga-nos onde e para quando, e deixe um contacto. No fim, o pedido segue por WhatsApp ou email, já escrito.',
  quoteRef: 'Ref. do pedido',
  quoteTagNote: 'A etiqueta preenche-se enquanto escreve.',
  noJs: 'Preencha os quatro passos e envie por email.',
  optional: 'opcional',
  blank: 'Em branco',
  publicSub: 'Alvará nº 4511',
  noRelated: 'As obras públicas não fazem parte do portefólio fotográfico deste site. Fale connosco para saber mais.',
  step: 'Passo',
  of: 'de',
  pref: { telefone: 'Telefone', whatsapp: 'WhatsApp', email: 'Email' },
  // Contactos
  contactH: 'Contactos',
  contactLead: 'Telefone, WhatsApp ou email: escolha o que lhe for mais prático.',
  mobile: 'Telemóvel',
  landline: 'Telefone fixo',
  quoteLink: 'Preferir o pedido guiado',
  // Empresa
  aboutH: 'A empresa',
  aboutLead: 'Construtora do Sul, Lda., em Quarteira. Constrói, reconstrói e remodela no Algarve desde 1985.',
  missionH: 'Missão',
  whoH: 'Onde estamos',
  teamH: 'A equipa',
  // Privacidade
  privacyH: 'Política de privacidade',
  privacyLead: 'Como tratamos os dados de um pedido de orçamento. Este site não usa cookies.',
} as const;
