// Textos próprios da variante "Mapa de Quantidades" (PT/EN). Só estrutura e chamadas; nenhum facto novo.
import type { Lang } from '../../lib/site';
type T = Record<Lang, string>;

export const C = {
  h1: { pt: 'Construímos, reconstruímos e remodelamos no Algarve desde 1985.', en: 'We build, rebuild and renovate in the Algarve, since 1985.' },
  col: {
    art: { pt: 'Art.', en: 'Item' },
    desc: { pt: 'Descrição', en: 'Description' },
    un: { pt: 'Un.', en: 'Unit' },
    qt: { pt: 'Qt.', en: 'Qty' },
    annex: { pt: 'Anexo', en: 'Annex' },
  } satisfies Record<string, T>,
  unitPhotos: { pt: 'fot.', en: 'ph.' },
  facts: {
    permit: { pt: 'Alvará', en: 'Permit' },
    seat: { pt: 'Sede', en: 'Head office' },
    area: { pt: 'Área', en: 'Area' },
    since: { pt: 'Desde', en: 'Since' },
    legal: { pt: 'Denominação', en: 'Legal name' },
    seatValue: { pt: 'Quarteira, Algarve', en: 'Quarteira, Algarve' },
  } satisfies Record<string, T>,
  servicesH: { pt: 'Mapa de trabalhos', en: 'Schedule of works' },
  servicesLead: {
    pt: 'Seis artigos, uma só empresa. Cada artigo abre a sua página, com os trabalhos incluídos e as obras que o mostram.',
    en: 'Six items, one company. Each item opens its own page, with the work it includes and the projects that show it.',
  },
  worksH: { pt: 'Anexo A: obras realizadas', en: 'Annex A: completed work' },
  worksLead: {
    pt: 'Fotografias de obras concluídas pela Civilsul. Cada prancha tem o seu código e a sua página.',
    en: 'Photographs of work completed by Civilsul. Each plate has its own code and its own page.',
  },
  allAnnex: { pt: 'Ver o Anexo A completo', en: 'See the full Annex A' },
  companyH: { pt: 'Quem assina a obra', en: 'Who signs the work' },
  processH: { pt: 'Como trabalhamos', en: 'How we work' },
  tradesH: { pt: 'Lista completa de trabalhos', en: 'Full list of trades' },
  tradesLead: {
    pt: 'A lista original de ofícios da Civilsul, para quem procura um trabalho específico.',
    en: 'Civilsul’s original list of trades, for anyone looking for one specific job.',
  },
  finalH: { pt: 'Traga-nos a sua obra.', en: 'Bring us your project.' },
  orCall: { pt: 'ou ligue', en: 'or call' },
  channels: { pt: 'Contactos diretos', en: 'Direct contacts' },
  mobile: { pt: 'Telemóvel', en: 'Mobile' },
  landline: { pt: 'Telefone', en: 'Phone' },
  filterAll: { pt: 'Todas', en: 'All' },
  filterLabel: { pt: 'Filtrar por tipo de obra', en: 'Filter by type of work' },
  showing: { pt: 'obras', en: 'projects' },
  kind: { pt: 'Tipo', en: 'Type' },
  place: { pt: 'Local', en: 'Place' },
  client: { pt: 'Cliente', en: 'Client' },
  service: { pt: 'Serviço', en: 'Service' },
  photos: { pt: 'Fotografias', en: 'Photographs' },
  prev: { pt: 'Obra anterior', en: 'Previous project' },
  next: { pt: 'Obra seguinte', en: 'Next project' },
  workCta: { pt: 'Quer uma obra como esta?', en: 'Want work like this?' },
  serviceCta: { pt: 'Peça orçamento para este trabalho', en: 'Request a quote for this work' },
  otherServices: { pt: 'Outros artigos', en: 'Other items' },
  includedH: { pt: 'Trabalhos incluídos', en: 'Work included' },
  noRelated: { pt: 'Sem fotografias publicadas para este artigo.', en: 'No photographs published for this item yet.' },
  quoteH: { pt: 'Pedido de orçamento', en: 'Quote request' },
  quoteLead: {
    pt: 'Quatro passos. À direita, o seu pedido preenche-se enquanto escreve; no fim envia-o por WhatsApp ou email.',
    en: 'Four steps. On the right, your request fills in as you type; at the end you send it via WhatsApp or email.',
  },
  sheetNo: { pt: 'nº', en: 'no.' },
  sheetTo: { pt: 'Para', en: 'To' },
  sheetDate: { pt: 'Data', en: 'Date' },
  sheetFoot: { pt: 'Rascunho do cliente. A Civilsul responde com o orçamento artigo a artigo.', en: 'Client draft. Civilsul replies with a quote itemised line by line.' },
  step: { pt: 'Passo', en: 'Step' },
  pref: {
    telefone: { pt: 'Telefone', en: 'Phone' },
    whatsapp: { pt: 'WhatsApp', en: 'WhatsApp' },
    email: { pt: 'Email', en: 'Email' },
  } satisfies Record<string, T>,
  optional: { pt: 'opcional', en: 'optional' },
  noJs: {
    pt: 'Sem JavaScript, todos os passos ficam visíveis e o botão abre o seu programa de email.',
    en: 'Without JavaScript, every step is shown and the button opens your email app.',
  },
  contactH: { pt: 'Contactos', en: 'Contact' },
  aboutH: { pt: 'Construtora do Sul, Lda.', en: 'Construtora do Sul, Lda.' },
  missionH: { pt: 'Missão', en: 'Mission' },
  whoH: { pt: 'Onde estamos', en: 'Where we are' },
  teamH: { pt: 'Equipa', en: 'Team' },
  privacyH: { pt: 'Política de privacidade', en: 'Privacy policy' },
  home: { pt: 'Início', en: 'Home' },
  quoteGo: { pt: 'Preencher o pedido', en: 'Fill in the request' },
  writeUs: { pt: 'Escrever um email', en: 'Write an email' },
  chat: { pt: 'Conversar no WhatsApp', en: 'Chat on WhatsApp' },
  seeService: { pt: 'Ver artigo', en: 'Open item' },
  seeWork: { pt: 'Ver obra', en: 'Open project' },
  contents: { pt: 'Índice', en: 'Index' },
  total: { pt: 'Total', en: 'Total' },
  totalLine: (lang: Lang, arts: number, items: number, plates: number) =>
    lang === 'pt' ? `${arts} artigos · ${plates} pranchas em anexo` : `${arts} items · ${plates} plates in annex`,
  aboutLead: {
    pt: 'Construtora do Sul, Lda., com sede em Quarteira. Alvará nº 4511 desde 1985; obras no Algarve e no restante país.',
    en: 'Construtora do Sul, Lda., based in Quarteira. Construction permit nº 4511 since 1985; working in the Algarve and across Portugal.',
  },
  motto: { pt: 'Lema', en: 'Motto' },
  bill: {
    pt: { type: 'Tipo de obra', property: 'Imóvel', place: 'Localidade', area: 'Área', timing: 'Início', state: 'Projeto', details: 'Descrição', name: 'Nome', phone: 'Telefone', email: 'Email', contactPref: 'Contacto preferido' },
    en: { type: 'Type of work', property: 'Property', place: 'Town', area: 'Area', timing: 'Start', state: 'Design', details: 'Description', name: 'Name', phone: 'Phone', email: 'Email', contactPref: 'Preferred contact' },
  },
  sheetCols: { pt: ['Art.', 'Designação', 'Pedido'], en: ['Item', 'Heading', 'Request'] },
  stripTitle: { pt: 'Pedido nº', en: 'Request no.' },
  stripOf: { pt: 'de', en: 'of' },
  stripArts: { pt: 'artigos', en: 'items' },
  stripEmpty: { pt: 'Ainda sem artigos preenchidos', en: 'No items filled in yet' },
  stripOpen: { pt: 'Ver o pedido', en: 'View the request' },
} as const;

export const t = (x: T, lang: Lang) => x[lang];
