// Textos próprios da variante "Aviso de Obra". Só rótulos e frases de ligação: nenhum facto novo.
// Os factos (1985, alvará 4511, morada, contactos, serviços, obras) vêm de src/lib/site.ts e src/content/*.
import type { Lang } from '../../lib/site';

const C = {
  pt: {
    band: 'Civilsul · Construtora do Sul, Lda.',
    aviso: 'Aviso',
    heroTitle: 'Construímos no Algarve desde 1985.',
    heroLabels: { permit: 'Alvará nº', seat: 'Sede', works: 'Obras', phone: 'Telefone' },
    heroSeat: 'Quarteira, Algarve',
    heroWorks: 'Moradias, reconstrução, remodelações, piscinas, obras públicas',
    field: {
      contractor: 'Entidade executante',
      permit: 'Alvará de construção nº',
      since: 'Em atividade desde',
      seat: 'Sede',
      area: 'Área de atuação',
      kind: 'Natureza da obra',
      place: 'Local',
      client: 'Dono da obra',
      service: 'Serviço',
      mobile: 'Telemóvel',
      landline: 'Telefone fixo',
      email: 'Email',
      whatsapp: 'WhatsApp',
      address: 'Morada',
    },
    servicesTitle: 'Da fundação aos acabamentos, a mesma empresa.',
    servicesLead: 'Seis frentes de trabalho, cada uma com a sua página: o que inclui e as obras onde a fizemos.',
    seeService: 'Ver serviço',
    worksTitle: 'Obras acabadas',
    worksLead: 'Casas construídas e reconstruídas, apartamentos remodelados, fachadas preservadas, piscinas e exteriores.',
    seeAllWorks: 'Ver todas as obras',
    whoTitle: 'Quem constrói',
    moreAbout: 'Sobre a empresa',
    processTitle: 'Como decorre uma obra',
    tradesTitle: 'Todos os ofícios',
    tradesLead: 'A lista completa de trabalhos, para quem procura um ofício específico.',
    blankTitle: 'A sua obra começa por um aviso em branco.',
    blankLead: 'Diga-nos que obra quer fazer, onde e para quando. Em quatro passos, o pedido fica pronto a enviar por WhatsApp ou email.',
    blankFields: ['Natureza da obra', 'Local', 'Início previsto', 'Dono da obra'],
    blankCta: 'Preencher o pedido',
    orCall: 'Ou fale connosco',
    servicesH1: 'Serviços de construção civil no Algarve',
    servicesIntro: 'Moradias, reconstrução, remodelações, piscinas, telhados e obras públicas. As especialidades ficam com a mesma equipa, das fundações aos acabamentos.',
    otherServices: 'Outros serviços',
    serviceCtaTitle: 'Tem uma obra deste tipo?',
    serviceCtaText: 'Conte-nos o que quer fazer. O pedido já segue com este tipo de obra escolhido.',
    worksH1: 'Obras realizadas',
    worksIntro: 'Cada obra tem a sua página, com as fotografias em grande. Filtre pelo tipo de trabalho.',
    filterLabel: 'Filtrar por tipo de obra',
    all: 'Todas',
    showing: 'A mostrar',
    prevWork: 'Obra anterior',
    nextWork: 'Obra seguinte',
    workCtaTitle: 'Tem uma obra parecida em mente?',
    workCtaText: 'Descreva-nos a sua. Respondemos por telefone, WhatsApp ou email, como preferir.',
    executedBy: 'Construtora do Sul, Lda. · Alvará nº 4511',
    quoteH1: 'Pedido de orçamento',
    quoteIntro: 'Preencha o aviso da sua obra. Os campos ficam escritos na placa à medida que responde; no fim, envie-a por WhatsApp ou email.',
    boardTitle: 'Aviso da sua obra',
    boardNote: 'Placa preenchida por si. Nada é enviado até carregar num dos botões de envio.',
    stepOf: 'Passo',
    contactH1: 'Contactos',
    contactCta: 'Prefere escrever? Faça o pedido guiado.',
    aboutH1: 'Construtora do Sul, Lda.',
    aboutLead: 'A Civilsul constrói, reconstrói e remodela no Algarve desde 1985, com o alvará nº 4511.',
    missionTitle: 'Missão',
    teamTitle: 'Equipa técnica',
    whereTitle: 'Onde estamos',
    privacyH1: 'Política de privacidade',
    quoteShort: 'Orçamento',
    menuLabel: 'Menu principal',
    navLabel: 'Navegação',
    footerNav: 'Páginas',
    contactsTitle: 'Contactos',
    breadcrumbHome: 'Início',
  },
  en: {
    band: 'Civilsul · Construtora do Sul, Lda.',
    aviso: 'Site notice',
    heroTitle: 'Building in the Algarve since 1985.',
    heroLabels: { permit: 'Permit nº', seat: 'Head office', works: 'Works', phone: 'Phone' },
    heroSeat: 'Quarteira, Algarve',
    heroWorks: 'Houses, rebuilding, renovations, pools, public works',
    field: {
      contractor: 'Contractor',
      permit: 'Construction permit nº',
      since: 'Working since',
      seat: 'Head office',
      area: 'Area covered',
      kind: 'Type of work',
      place: 'Location',
      client: 'Client',
      service: 'Service',
      mobile: 'Mobile',
      landline: 'Landline',
      email: 'Email',
      whatsapp: 'WhatsApp',
      address: 'Address',
    },
    servicesTitle: 'From foundations to finishes, one company.',
    servicesLead: 'Six lines of work, each with its own page: what it includes and the projects where we did it.',
    seeService: 'See service',
    worksTitle: 'Finished work',
    worksLead: 'Houses built and rebuilt, apartments renovated, facades preserved, pools and outdoor works.',
    seeAllWorks: 'See all work',
    whoTitle: 'Who builds',
    moreAbout: 'About the company',
    processTitle: 'How a job runs',
    tradesTitle: 'Every trade',
    tradesLead: 'The full list of works, for anyone looking for a specific trade.',
    blankTitle: 'Your project starts with a blank board.',
    blankLead: 'Tell us what you want to build, where and when. In four steps the request is ready to send via WhatsApp or email.',
    blankFields: ['Type of work', 'Location', 'Planned start', 'Client'],
    blankCta: 'Fill in the request',
    orCall: 'Or talk to us',
    servicesH1: 'Building services in the Algarve',
    servicesIntro: 'Houses, rebuilding, renovations, pools, roofs and public works. The specialist trades stay with the same team, from foundations to finishes.',
    otherServices: 'Other services',
    serviceCtaTitle: 'Planning this kind of work?',
    serviceCtaText: 'Tell us what you want to do. The request opens with this type of work already selected.',
    worksH1: 'Completed work',
    worksIntro: 'Every project has its own page, with the photographs shown large. Filter by type of work.',
    filterLabel: 'Filter by type of work',
    all: 'All',
    showing: 'Showing',
    prevWork: 'Previous project',
    nextWork: 'Next project',
    workCtaTitle: 'Have something similar in mind?',
    workCtaText: 'Describe your project. We reply by phone, WhatsApp or email, whichever you prefer.',
    executedBy: 'Construtora do Sul, Lda. · Permit nº 4511',
    quoteH1: 'Quote request',
    quoteIntro: 'Fill in the board for your project. Your answers are written onto the board as you go; at the end, send it via WhatsApp or email.',
    boardTitle: 'Your project board',
    boardNote: 'Filled in by you. Nothing is sent until you press one of the send buttons.',
    stepOf: 'Step',
    contactH1: 'Contact',
    contactCta: 'Prefer to write? Use the guided request.',
    aboutH1: 'Construtora do Sul, Lda.',
    aboutLead: 'Civilsul has built, rebuilt and renovated in the Algarve since 1985, under construction permit nº 4511.',
    missionTitle: 'Mission',
    teamTitle: 'Technical team',
    whereTitle: 'Where we are',
    privacyH1: 'Privacy policy',
    quoteShort: 'Quote',
    menuLabel: 'Main menu',
    navLabel: 'Navigation',
    footerNav: 'Pages',
    contactsTitle: 'Contact',
    breadcrumbHome: 'Home',
  },
};

export const copy = (lang: Lang) => C[lang];

/** Opções de preferência de contacto do pedido (radio "pref"). */
export const PREF = [
  { id: 'telefone', label: { pt: 'Telefone', en: 'Phone' } },
  { id: 'whatsapp', label: { pt: 'WhatsApp', en: 'WhatsApp' } },
  { id: 'email', label: { pt: 'Email', en: 'Email' } },
];

/** Serviço → valor pré-selecionado no pedido (?tipo=). */
export const SERVICE_TO_TYPE: Record<string, string> = {
  moradias: 'moradia',
  reconstrucao: 'reconstrucao',
  remodelacoes: 'remodelacao',
  piscinas: 'piscina',
  telhados: 'telhado',
  'obras-publicas': 'outro',
};
